# syntax=docker/dockerfile:1

ARG ICE_VERSION=0.17.0


FROM --platform=$BUILDPLATFORM golang:1.26.6-bookworm AS source

WORKDIR /src

COPY go.mod go.sum ./

RUN --mount=type=cache,id=orabbit-go-mod,target=/go/pkg/mod,sharing=locked \
    go mod download

COPY cmd ./cmd
COPY internal ./internal


# ------------------------------------------------------------
# Build master
# ------------------------------------------------------------

FROM source AS build-master

ARG TARGETOS
ARG TARGETARCH

RUN --mount=type=cache,id=orabbit-go-build-${TARGETOS}-${TARGETARCH},target=/root/.cache/go-build,sharing=locked \
    --mount=type=cache,id=orabbit-go-mod,target=/go/pkg/mod,sharing=locked \
    CGO_ENABLED=0 \
    GOOS=${TARGETOS} \
    GOARCH=${TARGETARCH} \
    go build \
      -trimpath \
      -ldflags="-s -w" \
      -o /out/orabbit-master \
      ./cmd/master


# ------------------------------------------------------------
# Build worker
# ------------------------------------------------------------

FROM source AS build-worker

ARG TARGETOS
ARG TARGETARCH

RUN --mount=type=cache,id=orabbit-go-build-${TARGETOS}-${TARGETARCH},target=/root/.cache/go-build,sharing=locked \
    --mount=type=cache,id=orabbit-go-mod,target=/go/pkg/mod,sharing=locked \
    CGO_ENABLED=0 \
    GOOS=${TARGETOS} \
    GOARCH=${TARGETARCH} \
    go build \
      -trimpath \
      -ldflags="-s -w" \
      -o /out/orabbit-worker \
      ./cmd/worker


# ------------------------------------------------------------
# Worker runtime base
# ------------------------------------------------------------

FROM debian:bookworm-slim AS runtime-base

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        ca-certificates \
        tzdata \
    && rm -rf /var/lib/apt/lists/*

# Unprivileged runtime user. Directories that become volumes are created here
# so new named volumes inherit this ownership.
RUN groupadd --system --gid 10001 orabbit \
    && useradd --system --uid 10001 --gid orabbit --home-dir /var/lib/orabbit --shell /usr/sbin/nologin orabbit \
    && install -d -o orabbit -g orabbit -m 0700 /var/lib/orabbit /var/lib/orabbit/identity

WORKDIR /var/lib/orabbit


# ------------------------------------------------------------
# Ice binary
# ------------------------------------------------------------

ARG ICE_VERSION

FROM altinity/ice:${ICE_VERSION} AS ice-bin


# ------------------------------------------------------------
# Master runtime base
# ------------------------------------------------------------

FROM eclipse-temurin:21-jre-jammy AS master-runtime-base

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        ca-certificates \
        tzdata \
    && rm -rf /var/lib/apt/lists/*

COPY --from=ice-bin /usr/local/bin/ice /usr/local/bin/ice

RUN chmod 0755 /usr/local/bin/ice

RUN groupadd --system --gid 10001 orabbit \
    && useradd --system --uid 10001 --gid orabbit --home-dir /var/lib/orabbit --shell /usr/sbin/nologin orabbit \
    && install -d -o orabbit -g orabbit -m 0700 /var/lib/orabbit

WORKDIR /var/lib/orabbit


# ------------------------------------------------------------
# Master
# ------------------------------------------------------------

FROM master-runtime-base AS master

COPY --from=build-master /out/orabbit-master /usr/local/bin/orabbit-master

USER 10001:10001

ENTRYPOINT ["/usr/local/bin/orabbit-master"]


# ------------------------------------------------------------
# Worker
# ------------------------------------------------------------

FROM runtime-base AS worker

COPY --from=build-worker /out/orabbit-worker /usr/local/bin/orabbit-worker

USER 10001:10001

ENTRYPOINT ["/usr/local/bin/orabbit-worker"]
