// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/controlplane.proto

package grpcpb

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterWorkerRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	WorkerId         string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`                         // optional; if empty master assigns
	Addr             string                 `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`                                                 // for observability only
	CapabilitiesJson string                 `protobuf:"bytes,3,opt,name=capabilities_json,json=capabilitiesJson,proto3" json:"capabilities_json,omitempty"` // opaque
	BootId           string                 `protobuf:"bytes,4,opt,name=boot_id,json=bootId,proto3" json:"boot_id,omitempty"`
	Hostname         string                 `protobuf:"bytes,5,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Pid              int32                  `protobuf:"varint,6,opt,name=pid,proto3" json:"pid,omitempty"`
	Version          string                 `protobuf:"bytes,7,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RegisterWorkerRequest) Reset() {
	*x = RegisterWorkerRequest{}
	mi := &file_proto_controlplane_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterWorkerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterWorkerRequest) ProtoMessage() {}

func (x *RegisterWorkerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_controlplane_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterWorkerRequest.ProtoReflect.Descriptor instead.
func (*RegisterWorkerRequest) Descriptor() ([]byte, []int) {
	return file_proto_controlplane_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterWorkerRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *RegisterWorkerRequest) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *RegisterWorkerRequest) GetCapabilitiesJson() string {
	if x != nil {
		return x.CapabilitiesJson
	}
	return ""
}

func (x *RegisterWorkerRequest) GetBootId() string {
	if x != nil {
		return x.BootId
	}
	return ""
}

func (x *RegisterWorkerRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *RegisterWorkerRequest) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *RegisterWorkerRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type RegisterWorkerResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	WorkerId            string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	HeartbeatIntervalMs int64                  `protobuf:"varint,2,opt,name=heartbeat_interval_ms,json=heartbeatIntervalMs,proto3" json:"heartbeat_interval_ms,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *RegisterWorkerResponse) Reset() {
	*x = RegisterWorkerResponse{}
	mi := &file_proto_controlplane_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterWorkerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterWorkerResponse) ProtoMessage() {}

func (x *RegisterWorkerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_controlplane_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterWorkerResponse.ProtoReflect.Descriptor instead.
func (*RegisterWorkerResponse) Descriptor() ([]byte, []int) {
	return file_proto_controlplane_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterWorkerResponse) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *RegisterWorkerResponse) GetHeartbeatIntervalMs() int64 {
	if x != nil {
		return x.HeartbeatIntervalMs
	}
	return 0
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	NowUnixMs     int64                  `protobuf:"varint,2,opt,name=now_unix_ms,json=nowUnixMs,proto3" json:"now_unix_ms,omitempty"`
	BootId        string                 `protobuf:"bytes,3,opt,name=boot_id,json=bootId,proto3" json:"boot_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_proto_controlplane_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_controlplane_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_proto_controlplane_proto_rawDescGZIP(), []int{2}
}

func (x *HeartbeatRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *HeartbeatRequest) GetNowUnixMs() int64 {
	if x != nil {
		return x.NowUnixMs
	}
	return 0
}

func (x *HeartbeatRequest) GetBootId() string {
	if x != nil {
		return x.BootId
	}
	return ""
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_proto_controlplane_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_controlplane_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_proto_controlplane_proto_rawDescGZIP(), []int{3}
}

type RequestTaskRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	WorkerId         string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	CapabilitiesJson string                 `protobuf:"bytes,2,opt,name=capabilities_json,json=capabilitiesJson,proto3" json:"capabilities_json,omitempty"`
	// Current value is 5. The master accepts an exact match only; see
	// docs/WORKER_PROTOCOL_COMPATIBILITY.md.
	ProtocolVersion int32  `protobuf:"varint,3,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	BootId          string `protobuf:"bytes,4,opt,name=boot_id,json=bootId,proto3" json:"boot_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RequestTaskRequest) Reset() {
	*x = RequestTaskRequest{}
	mi := &file_proto_controlplane_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestTaskRequest) ProtoMessage() {}

func (x *RequestTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_controlplane_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestTaskRequest.ProtoReflect.Descriptor instead.
func (*RequestTaskRequest) Descriptor() ([]byte, []int) {
	return file_proto_controlplane_proto_rawDescGZIP(), []int{4}
}

func (x *RequestTaskRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *RequestTaskRequest) GetCapabilitiesJson() string {
	if x != nil {
		return x.CapabilitiesJson
	}
	return ""
}

func (x *RequestTaskRequest) GetProtocolVersion() int32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *RequestTaskRequest) GetBootId() string {
	if x != nil {
		return x.BootId
	}
	return ""
}

type RequestTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *TaskAssignment        `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"` // if task.task_id is empty, no work
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestTaskResponse) Reset() {
	*x = RequestTaskResponse{}
	mi := &file_proto_controlplane_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestTaskResponse) ProtoMessage() {}

func (x *RequestTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_controlplane_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestTaskResponse.ProtoReflect.Descriptor instead.
func (*RequestTaskResponse) Descriptor() ([]byte, []int) {
	return file_proto_controlplane_proto_rawDescGZIP(), []int{5}
}

func (x *RequestTaskResponse) GetTask() *TaskAssignment {
	if x != nil {
		return x.Task
	}
	return nil
}

type TaskAssignment struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	TaskId              string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	RunId               string                 `protobuf:"bytes,2,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	JobId               string                 `protobuf:"bytes,3,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	TaskIndex           int32                  `protobuf:"varint,4,opt,name=task_index,json=taskIndex,proto3" json:"task_index,omitempty"`
	CorrelationId       string                 `protobuf:"bytes,5,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	AttemptId           string                 `protobuf:"bytes,6,opt,name=attempt_id,json=attemptId,proto3" json:"attempt_id,omitempty"`
	FencingToken        string                 `protobuf:"bytes,7,opt,name=fencing_token,json=fencingToken,proto3" json:"fencing_token,omitempty"` // secret ownership credential; do not log
	AttemptNumber       int32                  `protobuf:"varint,8,opt,name=attempt_number,json=attemptNumber,proto3" json:"attempt_number,omitempty"`
	LeaseDeadlineUnixMs int64                  `protobuf:"varint,9,opt,name=lease_deadline_unix_ms,json=leaseDeadlineUnixMs,proto3" json:"lease_deadline_unix_ms,omitempty"`
	// Planning / partition
	PartitionSpecJson string `protobuf:"bytes,10,opt,name=partition_spec_json,json=partitionSpecJson,proto3" json:"partition_spec_json,omitempty"`
	// Source
	SourceEngine string `protobuf:"bytes,20,opt,name=source_engine,json=sourceEngine,proto3" json:"source_engine,omitempty"` // e.g. mssql, postgres
	SourceDsn    string `protobuf:"bytes,21,opt,name=source_dsn,json=sourceDsn,proto3" json:"source_dsn,omitempty"`          // decrypted DSN; do not log
	SourceSql    string `protobuf:"bytes,22,opt,name=source_sql,json=sourceSql,proto3" json:"source_sql,omitempty"`
	// Target (S3/MinIO)
	S3Endpoint        string `protobuf:"bytes,30,opt,name=s3_endpoint,json=s3Endpoint,proto3" json:"s3_endpoint,omitempty"`
	S3Region          string `protobuf:"bytes,31,opt,name=s3_region,json=s3Region,proto3" json:"s3_region,omitempty"`
	S3Bucket          string `protobuf:"bytes,32,opt,name=s3_bucket,json=s3Bucket,proto3" json:"s3_bucket,omitempty"`
	S3Prefix          string `protobuf:"bytes,33,opt,name=s3_prefix,json=s3Prefix,proto3" json:"s3_prefix,omitempty"` // base prefix for output objects
	S3ForcePathStyle  bool   `protobuf:"varint,34,opt,name=s3_force_path_style,json=s3ForcePathStyle,proto3" json:"s3_force_path_style,omitempty"`
	S3AccessKeyId     string `protobuf:"bytes,35,opt,name=s3_access_key_id,json=s3AccessKeyId,proto3" json:"s3_access_key_id,omitempty"`             // do not log
	S3SecretAccessKey string `protobuf:"bytes,36,opt,name=s3_secret_access_key,json=s3SecretAccessKey,proto3" json:"s3_secret_access_key,omitempty"` // do not log
	S3SessionToken    string `protobuf:"bytes,37,opt,name=s3_session_token,json=s3SessionToken,proto3" json:"s3_session_token,omitempty"`            // optional
	// Output controls
	TargetFileBytes int64    `protobuf:"varint,40,opt,name=target_file_bytes,json=targetFileBytes,proto3" json:"target_file_bytes,omitempty"`
	PartitionKeys   []string `protobuf:"bytes,43,rep,name=partition_keys,json=partitionKeys,proto3" json:"partition_keys,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TaskAssignment) Reset() {
	*x = TaskAssignment{}
	mi := &file_proto_controlplane_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskAssignment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskAssignment) ProtoMessage() {}

func (x *TaskAssignment) ProtoReflect() protoreflect.Message {
	mi := &file_proto_controlplane_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskAssignment.ProtoReflect.Descriptor instead.
func (*TaskAssignment) Descriptor() ([]byte, []int) {
	return file_proto_controlplane_proto_rawDescGZIP(), []int{6}
}

func (x *TaskAssignment) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskAssignment) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *TaskAssignment) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *TaskAssignment) GetTaskIndex() int32 {
	if x != nil {
		return x.TaskIndex
	}
	return 0
}

func (x *TaskAssignment) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *TaskAssignment) GetAttemptId() string {
	if x != nil {
		return x.AttemptId
	}
	return ""
}

func (x *TaskAssignment) GetFencingToken() string {
	if x != nil {
		return x.FencingToken
	}
	return ""
}

func (x *TaskAssignment) GetAttemptNumber() int32 {
	if x != nil {
		return x.AttemptNumber
	}
	return 0
}

func (x *TaskAssignment) GetLeaseDeadlineUnixMs() int64 {
	if x != nil {
		return x.LeaseDeadlineUnixMs
	}
	return 0
}

func (x *TaskAssignment) GetPartitionSpecJson() string {
	if x != nil {
		return x.PartitionSpecJson
	}
	return ""
}

func (x *TaskAssignment) GetSourceEngine() string {
	if x != nil {
		return x.SourceEngine
	}
	return ""
}

func (x *TaskAssignment) GetSourceDsn() string {
	if x != nil {
		return x.SourceDsn
	}
	return ""
}

func (x *TaskAssignment) GetSourceSql() string {
	if x != nil {
		return x.SourceSql
	}
	return ""
}

func (x *TaskAssignment) GetS3Endpoint() string {
	if x != nil {
		return x.S3Endpoint
	}
	return ""
}

func (x *TaskAssignment) GetS3Region() string {
	if x != nil {
		return x.S3Region
	}
	return ""
}

func (x *TaskAssignment) GetS3Bucket() string {
	if x != nil {
		return x.S3Bucket
	}
	return ""
}

func (x *TaskAssignment) GetS3Prefix() string {
	if x != nil {
		return x.S3Prefix
	}
	return ""
}

func (x *TaskAssignment) GetS3ForcePathStyle() bool {
	if x != nil {
		return x.S3ForcePathStyle
	}
	return false
}

func (x *TaskAssignment) GetS3AccessKeyId() string {
	if x != nil {
		return x.S3AccessKeyId
	}
	return ""
}

func (x *TaskAssignment) GetS3SecretAccessKey() string {
	if x != nil {
		return x.S3SecretAccessKey
	}
	return ""
}

func (x *TaskAssignment) GetS3SessionToken() string {
	if x != nil {
		return x.S3SessionToken
	}
	return ""
}

func (x *TaskAssignment) GetTargetFileBytes() int64 {
	if x != nil {
		return x.TargetFileBytes
	}
	return 0
}

func (x *TaskAssignment) GetPartitionKeys() []string {
	if x != nil {
		return x.PartitionKeys
	}
	return nil
}

type ReportTaskProgressRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	WorkerId          string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	TaskId            string                 `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	RunId             string                 `protobuf:"bytes,3,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	AttemptId         string                 `protobuf:"bytes,4,opt,name=attempt_id,json=attemptId,proto3" json:"attempt_id,omitempty"`
	FencingToken      string                 `protobuf:"bytes,5,opt,name=fencing_token,json=fencingToken,proto3" json:"fencing_token,omitempty"`
	BootId            string                 `protobuf:"bytes,6,opt,name=boot_id,json=bootId,proto3" json:"boot_id,omitempty"`
	RowsRead          int64                  `protobuf:"varint,10,opt,name=rows_read,json=rowsRead,proto3" json:"rows_read,omitempty"`
	BytesRead         int64                  `protobuf:"varint,11,opt,name=bytes_read,json=bytesRead,proto3" json:"bytes_read,omitempty"`
	BytesWritten      int64                  `protobuf:"varint,12,opt,name=bytes_written,json=bytesWritten,proto3" json:"bytes_written,omitempty"`
	UncompressedBytes int64                  `protobuf:"varint,13,opt,name=uncompressed_bytes,json=uncompressedBytes,proto3" json:"uncompressed_bytes,omitempty"`
	Message           string                 `protobuf:"bytes,20,opt,name=message,proto3" json:"message,omitempty"`
	FieldsJson        string                 `protobuf:"bytes,21,opt,name=fields_json,json=fieldsJson,proto3" json:"fields_json,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ReportTaskProgressRequest) Reset() {
	*x = ReportTaskProgressRequest{}
	mi := &file_proto_controlplane_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportTaskProgressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportTaskProgressRequest) ProtoMessage() {}

func (x *ReportTaskProgressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_controlplane_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportTaskProgressRequest.ProtoReflect.Descriptor instead.
func (*ReportTaskProgressRequest) Descriptor() ([]byte, []int) {
	return file_proto_controlplane_proto_rawDescGZIP(), []int{7}
}

func (x *ReportTaskProgressRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *ReportTaskProgressRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *ReportTaskProgressRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *ReportTaskProgressRequest) GetAttemptId() string {
	if x != nil {
		return x.AttemptId
	}
	return ""
}

func (x *ReportTaskProgressRequest) GetFencingToken() string {
	if x != nil {
		return x.FencingToken
	}
	return ""
}

func (x *ReportTaskProgressRequest) GetBootId() string {
	if x != nil {
		return x.BootId
	}
	return ""
}

func (x *ReportTaskProgressRequest) GetRowsRead() int64 {
	if x != nil {
		return x.RowsRead
	}
	return 0
}

func (x *ReportTaskProgressRequest) GetBytesRead() int64 {
	if x != nil {
		return x.BytesRead
	}
	return 0
}

func (x *ReportTaskProgressRequest) GetBytesWritten() int64 {
	if x != nil {
		return x.BytesWritten
	}
	return 0
}

func (x *ReportTaskProgressRequest) GetUncompressedBytes() int64 {
	if x != nil {
		return x.UncompressedBytes
	}
	return 0
}

func (x *ReportTaskProgressRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ReportTaskProgressRequest) GetFieldsJson() string {
	if x != nil {
		return x.FieldsJson
	}
	return ""
}

type ReportTaskProgressResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportTaskProgressResponse) Reset() {
	*x = ReportTaskProgressResponse{}
	mi := &file_proto_controlplane_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportTaskProgressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportTaskProgressResponse) ProtoMessage() {}

func (x *ReportTaskProgressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_controlplane_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportTaskProgressResponse.ProtoReflect.Descriptor instead.
func (*ReportTaskProgressResponse) Descriptor() ([]byte, []int) {
	return file_proto_controlplane_proto_rawDescGZIP(), []int{8}
}

type ReportTaskResultRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	WorkerId          string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	TaskId            string                 `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	RunId             string                 `protobuf:"bytes,3,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	AttemptId         string                 `protobuf:"bytes,4,opt,name=attempt_id,json=attemptId,proto3" json:"attempt_id,omitempty"`
	FencingToken      string                 `protobuf:"bytes,5,opt,name=fencing_token,json=fencingToken,proto3" json:"fencing_token,omitempty"`
	BootId            string                 `protobuf:"bytes,6,opt,name=boot_id,json=bootId,proto3" json:"boot_id,omitempty"`
	Status            string                 `protobuf:"bytes,10,opt,name=status,proto3" json:"status,omitempty"`                                 // SUCCEEDED, FAILED, or CANCELED
	ErrorMessage      string                 `protobuf:"bytes,11,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"` // if failed
	FailureClass      string                 `protobuf:"bytes,12,opt,name=failure_class,json=failureClass,proto3" json:"failure_class,omitempty"` // strongly typed classification
	RowsRead          int64                  `protobuf:"varint,20,opt,name=rows_read,json=rowsRead,proto3" json:"rows_read,omitempty"`
	BytesRead         int64                  `protobuf:"varint,21,opt,name=bytes_read,json=bytesRead,proto3" json:"bytes_read,omitempty"`
	BytesWritten      int64                  `protobuf:"varint,22,opt,name=bytes_written,json=bytesWritten,proto3" json:"bytes_written,omitempty"`
	UncompressedBytes int64                  `protobuf:"varint,23,opt,name=uncompressed_bytes,json=uncompressedBytes,proto3" json:"uncompressed_bytes,omitempty"`
	ParquetObjectKeys []string               `protobuf:"bytes,30,rep,name=parquet_object_keys,json=parquetObjectKeys,proto3" json:"parquet_object_keys,omitempty"`
	MaxHwmValue       string                 `protobuf:"bytes,31,opt,name=max_hwm_value,json=maxHwmValue,proto3" json:"max_hwm_value,omitempty"` // optional, as string
	Artifacts         []*ArtifactIntegrity   `protobuf:"bytes,32,rep,name=artifacts,proto3" json:"artifacts,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ReportTaskResultRequest) Reset() {
	*x = ReportTaskResultRequest{}
	mi := &file_proto_controlplane_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportTaskResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportTaskResultRequest) ProtoMessage() {}

func (x *ReportTaskResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_controlplane_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportTaskResultRequest.ProtoReflect.Descriptor instead.
func (*ReportTaskResultRequest) Descriptor() ([]byte, []int) {
	return file_proto_controlplane_proto_rawDescGZIP(), []int{9}
}

func (x *ReportTaskResultRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *ReportTaskResultRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *ReportTaskResultRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *ReportTaskResultRequest) GetAttemptId() string {
	if x != nil {
		return x.AttemptId
	}
	return ""
}

func (x *ReportTaskResultRequest) GetFencingToken() string {
	if x != nil {
		return x.FencingToken
	}
	return ""
}

func (x *ReportTaskResultRequest) GetBootId() string {
	if x != nil {
		return x.BootId
	}
	return ""
}

func (x *ReportTaskResultRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ReportTaskResultRequest) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *ReportTaskResultRequest) GetFailureClass() string {
	if x != nil {
		return x.FailureClass
	}
	return ""
}

func (x *ReportTaskResultRequest) GetRowsRead() int64 {
	if x != nil {
		return x.RowsRead
	}
	return 0
}

func (x *ReportTaskResultRequest) GetBytesRead() int64 {
	if x != nil {
		return x.BytesRead
	}
	return 0
}

func (x *ReportTaskResultRequest) GetBytesWritten() int64 {
	if x != nil {
		return x.BytesWritten
	}
	return 0
}

func (x *ReportTaskResultRequest) GetUncompressedBytes() int64 {
	if x != nil {
		return x.UncompressedBytes
	}
	return 0
}

func (x *ReportTaskResultRequest) GetParquetObjectKeys() []string {
	if x != nil {
		return x.ParquetObjectKeys
	}
	return nil
}

func (x *ReportTaskResultRequest) GetMaxHwmValue() string {
	if x != nil {
		return x.MaxHwmValue
	}
	return ""
}

func (x *ReportTaskResultRequest) GetArtifacts() []*ArtifactIntegrity {
	if x != nil {
		return x.Artifacts
	}
	return nil
}

type ArtifactIntegrity struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ObjectKey          string                 `protobuf:"bytes,1,opt,name=object_key,json=objectKey,proto3" json:"object_key,omitempty"`
	ByteSize           int64                  `protobuf:"varint,2,opt,name=byte_size,json=byteSize,proto3" json:"byte_size,omitempty"`
	Sha256             string                 `protobuf:"bytes,3,opt,name=sha256,proto3" json:"sha256,omitempty"`
	RowCount           int64                  `protobuf:"varint,4,opt,name=row_count,json=rowCount,proto3" json:"row_count,omitempty"`
	SchemaFingerprint  string                 `protobuf:"bytes,5,opt,name=schema_fingerprint,json=schemaFingerprint,proto3" json:"schema_fingerprint,omitempty"`
	RunId              string                 `protobuf:"bytes,6,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	TaskId             string                 `protobuf:"bytes,7,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	AttemptId          string                 `protobuf:"bytes,8,opt,name=attempt_id,json=attemptId,proto3" json:"attempt_id,omitempty"`
	AttemptNumber      int32                  `protobuf:"varint,9,opt,name=attempt_number,json=attemptNumber,proto3" json:"attempt_number,omitempty"`
	FileIndex          int32                  `protobuf:"varint,10,opt,name=file_index,json=fileIndex,proto3" json:"file_index,omitempty"`
	FormatVersion      int32                  `protobuf:"varint,11,opt,name=format_version,json=formatVersion,proto3" json:"format_version,omitempty"`
	VerificationMethod string                 `protobuf:"bytes,12,opt,name=verification_method,json=verificationMethod,proto3" json:"verification_method,omitempty"`
	VerificationStatus string                 `protobuf:"bytes,13,opt,name=verification_status,json=verificationStatus,proto3" json:"verification_status,omitempty"`
	VerifiedAt         string                 `protobuf:"bytes,14,opt,name=verified_at,json=verifiedAt,proto3" json:"verified_at,omitempty"`
	MaxHwm             string                 `protobuf:"bytes,15,opt,name=max_hwm,json=maxHwm,proto3" json:"max_hwm,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ArtifactIntegrity) Reset() {
	*x = ArtifactIntegrity{}
	mi := &file_proto_controlplane_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArtifactIntegrity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtifactIntegrity) ProtoMessage() {}

func (x *ArtifactIntegrity) ProtoReflect() protoreflect.Message {
	mi := &file_proto_controlplane_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtifactIntegrity.ProtoReflect.Descriptor instead.
func (*ArtifactIntegrity) Descriptor() ([]byte, []int) {
	return file_proto_controlplane_proto_rawDescGZIP(), []int{10}
}

func (x *ArtifactIntegrity) GetObjectKey() string {
	if x != nil {
		return x.ObjectKey
	}
	return ""
}

func (x *ArtifactIntegrity) GetByteSize() int64 {
	if x != nil {
		return x.ByteSize
	}
	return 0
}

func (x *ArtifactIntegrity) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

func (x *ArtifactIntegrity) GetRowCount() int64 {
	if x != nil {
		return x.RowCount
	}
	return 0
}

func (x *ArtifactIntegrity) GetSchemaFingerprint() string {
	if x != nil {
		return x.SchemaFingerprint
	}
	return ""
}

func (x *ArtifactIntegrity) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *ArtifactIntegrity) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *ArtifactIntegrity) GetAttemptId() string {
	if x != nil {
		return x.AttemptId
	}
	return ""
}

func (x *ArtifactIntegrity) GetAttemptNumber() int32 {
	if x != nil {
		return x.AttemptNumber
	}
	return 0
}

func (x *ArtifactIntegrity) GetFileIndex() int32 {
	if x != nil {
		return x.FileIndex
	}
	return 0
}

func (x *ArtifactIntegrity) GetFormatVersion() int32 {
	if x != nil {
		return x.FormatVersion
	}
	return 0
}

func (x *ArtifactIntegrity) GetVerificationMethod() string {
	if x != nil {
		return x.VerificationMethod
	}
	return ""
}

func (x *ArtifactIntegrity) GetVerificationStatus() string {
	if x != nil {
		return x.VerificationStatus
	}
	return ""
}

func (x *ArtifactIntegrity) GetVerifiedAt() string {
	if x != nil {
		return x.VerifiedAt
	}
	return ""
}

func (x *ArtifactIntegrity) GetMaxHwm() string {
	if x != nil {
		return x.MaxHwm
	}
	return ""
}

type RenewTaskLeaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	TaskId        string                 `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	AttemptId     string                 `protobuf:"bytes,3,opt,name=attempt_id,json=attemptId,proto3" json:"attempt_id,omitempty"`
	FencingToken  string                 `protobuf:"bytes,4,opt,name=fencing_token,json=fencingToken,proto3" json:"fencing_token,omitempty"`
	BootId        string                 `protobuf:"bytes,5,opt,name=boot_id,json=bootId,proto3" json:"boot_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenewTaskLeaseRequest) Reset() {
	*x = RenewTaskLeaseRequest{}
	mi := &file_proto_controlplane_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenewTaskLeaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenewTaskLeaseRequest) ProtoMessage() {}

func (x *RenewTaskLeaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_controlplane_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenewTaskLeaseRequest.ProtoReflect.Descriptor instead.
func (*RenewTaskLeaseRequest) Descriptor() ([]byte, []int) {
	return file_proto_controlplane_proto_rawDescGZIP(), []int{11}
}

func (x *RenewTaskLeaseRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *RenewTaskLeaseRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *RenewTaskLeaseRequest) GetAttemptId() string {
	if x != nil {
		return x.AttemptId
	}
	return ""
}

func (x *RenewTaskLeaseRequest) GetFencingToken() string {
	if x != nil {
		return x.FencingToken
	}
	return ""
}

func (x *RenewTaskLeaseRequest) GetBootId() string {
	if x != nil {
		return x.BootId
	}
	return ""
}

type RenewTaskLeaseResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	LeaseDeadlineUnixMs int64                  `protobuf:"varint,1,opt,name=lease_deadline_unix_ms,json=leaseDeadlineUnixMs,proto3" json:"lease_deadline_unix_ms,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *RenewTaskLeaseResponse) Reset() {
	*x = RenewTaskLeaseResponse{}
	mi := &file_proto_controlplane_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenewTaskLeaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenewTaskLeaseResponse) ProtoMessage() {}

func (x *RenewTaskLeaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_controlplane_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenewTaskLeaseResponse.ProtoReflect.Descriptor instead.
func (*RenewTaskLeaseResponse) Descriptor() ([]byte, []int) {
	return file_proto_controlplane_proto_rawDescGZIP(), []int{12}
}

func (x *RenewTaskLeaseResponse) GetLeaseDeadlineUnixMs() int64 {
	if x != nil {
		return x.LeaseDeadlineUnixMs
	}
	return 0
}

type AcquireUploadCapacityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	TaskId        string                 `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	AttemptId     string                 `protobuf:"bytes,3,opt,name=attempt_id,json=attemptId,proto3" json:"attempt_id,omitempty"`
	FencingToken  string                 `protobuf:"bytes,4,opt,name=fencing_token,json=fencingToken,proto3" json:"fencing_token,omitempty"`
	BootId        string                 `protobuf:"bytes,5,opt,name=boot_id,json=bootId,proto3" json:"boot_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcquireUploadCapacityRequest) Reset() {
	*x = AcquireUploadCapacityRequest{}
	mi := &file_proto_controlplane_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcquireUploadCapacityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcquireUploadCapacityRequest) ProtoMessage() {}

func (x *AcquireUploadCapacityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_controlplane_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcquireUploadCapacityRequest.ProtoReflect.Descriptor instead.
func (*AcquireUploadCapacityRequest) Descriptor() ([]byte, []int) {
	return file_proto_controlplane_proto_rawDescGZIP(), []int{13}
}

func (x *AcquireUploadCapacityRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *AcquireUploadCapacityRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *AcquireUploadCapacityRequest) GetAttemptId() string {
	if x != nil {
		return x.AttemptId
	}
	return ""
}

func (x *AcquireUploadCapacityRequest) GetFencingToken() string {
	if x != nil {
		return x.FencingToken
	}
	return ""
}

func (x *AcquireUploadCapacityRequest) GetBootId() string {
	if x != nil {
		return x.BootId
	}
	return ""
}

type AcquireUploadCapacityResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Acquired            bool                   `protobuf:"varint,1,opt,name=acquired,proto3" json:"acquired,omitempty"`
	LeaseId             string                 `protobuf:"bytes,2,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	LeaseToken          string                 `protobuf:"bytes,3,opt,name=lease_token,json=leaseToken,proto3" json:"lease_token,omitempty"` // secret capacity credential; do not log
	LeaseDeadlineUnixMs int64                  `protobuf:"varint,4,opt,name=lease_deadline_unix_ms,json=leaseDeadlineUnixMs,proto3" json:"lease_deadline_unix_ms,omitempty"`
	RetryAfterMs        int64                  `protobuf:"varint,5,opt,name=retry_after_ms,json=retryAfterMs,proto3" json:"retry_after_ms,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *AcquireUploadCapacityResponse) Reset() {
	*x = AcquireUploadCapacityResponse{}
	mi := &file_proto_controlplane_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcquireUploadCapacityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcquireUploadCapacityResponse) ProtoMessage() {}

func (x *AcquireUploadCapacityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_controlplane_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcquireUploadCapacityResponse.ProtoReflect.Descriptor instead.
func (*AcquireUploadCapacityResponse) Descriptor() ([]byte, []int) {
	return file_proto_controlplane_proto_rawDescGZIP(), []int{14}
}

func (x *AcquireUploadCapacityResponse) GetAcquired() bool {
	if x != nil {
		return x.Acquired
	}
	return false
}

func (x *AcquireUploadCapacityResponse) GetLeaseId() string {
	if x != nil {
		return x.LeaseId
	}
	return ""
}

func (x *AcquireUploadCapacityResponse) GetLeaseToken() string {
	if x != nil {
		return x.LeaseToken
	}
	return ""
}

func (x *AcquireUploadCapacityResponse) GetLeaseDeadlineUnixMs() int64 {
	if x != nil {
		return x.LeaseDeadlineUnixMs
	}
	return 0
}

func (x *AcquireUploadCapacityResponse) GetRetryAfterMs() int64 {
	if x != nil {
		return x.RetryAfterMs
	}
	return 0
}

type ReleaseUploadCapacityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	TaskId        string                 `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	AttemptId     string                 `protobuf:"bytes,3,opt,name=attempt_id,json=attemptId,proto3" json:"attempt_id,omitempty"`
	LeaseId       string                 `protobuf:"bytes,4,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	LeaseToken    string                 `protobuf:"bytes,5,opt,name=lease_token,json=leaseToken,proto3" json:"lease_token,omitempty"` // secret capacity credential; do not log
	BootId        string                 `protobuf:"bytes,6,opt,name=boot_id,json=bootId,proto3" json:"boot_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseUploadCapacityRequest) Reset() {
	*x = ReleaseUploadCapacityRequest{}
	mi := &file_proto_controlplane_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseUploadCapacityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseUploadCapacityRequest) ProtoMessage() {}

func (x *ReleaseUploadCapacityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_controlplane_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseUploadCapacityRequest.ProtoReflect.Descriptor instead.
func (*ReleaseUploadCapacityRequest) Descriptor() ([]byte, []int) {
	return file_proto_controlplane_proto_rawDescGZIP(), []int{15}
}

func (x *ReleaseUploadCapacityRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *ReleaseUploadCapacityRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *ReleaseUploadCapacityRequest) GetAttemptId() string {
	if x != nil {
		return x.AttemptId
	}
	return ""
}

func (x *ReleaseUploadCapacityRequest) GetLeaseId() string {
	if x != nil {
		return x.LeaseId
	}
	return ""
}

func (x *ReleaseUploadCapacityRequest) GetLeaseToken() string {
	if x != nil {
		return x.LeaseToken
	}
	return ""
}

func (x *ReleaseUploadCapacityRequest) GetBootId() string {
	if x != nil {
		return x.BootId
	}
	return ""
}

type ReleaseUploadCapacityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseUploadCapacityResponse) Reset() {
	*x = ReleaseUploadCapacityResponse{}
	mi := &file_proto_controlplane_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseUploadCapacityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseUploadCapacityResponse) ProtoMessage() {}

func (x *ReleaseUploadCapacityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_controlplane_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseUploadCapacityResponse.ProtoReflect.Descriptor instead.
func (*ReleaseUploadCapacityResponse) Descriptor() ([]byte, []int) {
	return file_proto_controlplane_proto_rawDescGZIP(), []int{16}
}

type ReportTaskResultResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportTaskResultResponse) Reset() {
	*x = ReportTaskResultResponse{}
	mi := &file_proto_controlplane_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportTaskResultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportTaskResultResponse) ProtoMessage() {}

func (x *ReportTaskResultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_controlplane_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportTaskResultResponse.ProtoReflect.Descriptor instead.
func (*ReportTaskResultResponse) Descriptor() ([]byte, []int) {
	return file_proto_controlplane_proto_rawDescGZIP(), []int{17}
}

func (x *ReportTaskResultResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *ReportTaskResultResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_controlplane_proto protoreflect.FileDescriptor

const file_proto_controlplane_proto_rawDesc = "" +
	"\n" +
	"\x18proto/controlplane.proto\x12\n" +
	"orabbit.v1\"\xd6\x01\n" +
	"\x15RegisterWorkerRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\x12+\n" +
	"\x11capabilities_json\x18\x03 \x01(\tR\x10capabilitiesJson\x12\x17\n" +
	"\aboot_id\x18\x04 \x01(\tR\x06bootId\x12\x1a\n" +
	"\bhostname\x18\x05 \x01(\tR\bhostname\x12\x10\n" +
	"\x03pid\x18\x06 \x01(\x05R\x03pid\x12\x18\n" +
	"\aversion\x18\a \x01(\tR\aversion\"i\n" +
	"\x16RegisterWorkerResponse\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x122\n" +
	"\x15heartbeat_interval_ms\x18\x02 \x01(\x03R\x13heartbeatIntervalMs\"h\n" +
	"\x10HeartbeatRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12\x1e\n" +
	"\vnow_unix_ms\x18\x02 \x01(\x03R\tnowUnixMs\x12\x17\n" +
	"\aboot_id\x18\x03 \x01(\tR\x06bootId\"\x13\n" +
	"\x11HeartbeatResponse\"\xa2\x01\n" +
	"\x12RequestTaskRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12+\n" +
	"\x11capabilities_json\x18\x02 \x01(\tR\x10capabilitiesJson\x12)\n" +
	"\x10protocol_version\x18\x03 \x01(\x05R\x0fprotocolVersion\x12\x17\n" +
	"\aboot_id\x18\x04 \x01(\tR\x06bootId\"E\n" +
	"\x13RequestTaskResponse\x12.\n" +
	"\x04task\x18\x01 \x01(\v2\x1a.orabbit.v1.TaskAssignmentR\x04task\"\xff\x06\n" +
	"\x0eTaskAssignment\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x15\n" +
	"\x06run_id\x18\x02 \x01(\tR\x05runId\x12\x15\n" +
	"\x06job_id\x18\x03 \x01(\tR\x05jobId\x12\x1d\n" +
	"\n" +
	"task_index\x18\x04 \x01(\x05R\ttaskIndex\x12%\n" +
	"\x0ecorrelation_id\x18\x05 \x01(\tR\rcorrelationId\x12\x1d\n" +
	"\n" +
	"attempt_id\x18\x06 \x01(\tR\tattemptId\x12#\n" +
	"\rfencing_token\x18\a \x01(\tR\ffencingToken\x12%\n" +
	"\x0eattempt_number\x18\b \x01(\x05R\rattemptNumber\x123\n" +
	"\x16lease_deadline_unix_ms\x18\t \x01(\x03R\x13leaseDeadlineUnixMs\x12.\n" +
	"\x13partition_spec_json\x18\n" +
	" \x01(\tR\x11partitionSpecJson\x12#\n" +
	"\rsource_engine\x18\x14 \x01(\tR\fsourceEngine\x12\x1d\n" +
	"\n" +
	"source_dsn\x18\x15 \x01(\tR\tsourceDsn\x12\x1d\n" +
	"\n" +
	"source_sql\x18\x16 \x01(\tR\tsourceSql\x12\x1f\n" +
	"\vs3_endpoint\x18\x1e \x01(\tR\n" +
	"s3Endpoint\x12\x1b\n" +
	"\ts3_region\x18\x1f \x01(\tR\bs3Region\x12\x1b\n" +
	"\ts3_bucket\x18  \x01(\tR\bs3Bucket\x12\x1b\n" +
	"\ts3_prefix\x18! \x01(\tR\bs3Prefix\x12-\n" +
	"\x13s3_force_path_style\x18\" \x01(\bR\x10s3ForcePathStyle\x12'\n" +
	"\x10s3_access_key_id\x18# \x01(\tR\rs3AccessKeyId\x12/\n" +
	"\x14s3_secret_access_key\x18$ \x01(\tR\x11s3SecretAccessKey\x12(\n" +
	"\x10s3_session_token\x18% \x01(\tR\x0es3SessionToken\x12*\n" +
	"\x11target_file_bytes\x18( \x01(\x03R\x0ftargetFileBytes\x12%\n" +
	"\x0epartition_keys\x18+ \x03(\tR\rpartitionKeysJ\x04\b)\x10*J\x04\b*\x10+R\x11max_rows_per_fileR\x10fetch_limit_rows\"\x90\x03\n" +
	"\x19ReportTaskProgressRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\tR\x06taskId\x12\x15\n" +
	"\x06run_id\x18\x03 \x01(\tR\x05runId\x12\x1d\n" +
	"\n" +
	"attempt_id\x18\x04 \x01(\tR\tattemptId\x12#\n" +
	"\rfencing_token\x18\x05 \x01(\tR\ffencingToken\x12\x17\n" +
	"\aboot_id\x18\x06 \x01(\tR\x06bootId\x12\x1b\n" +
	"\trows_read\x18\n" +
	" \x01(\x03R\browsRead\x12\x1d\n" +
	"\n" +
	"bytes_read\x18\v \x01(\x03R\tbytesRead\x12#\n" +
	"\rbytes_written\x18\f \x01(\x03R\fbytesWritten\x12-\n" +
	"\x12uncompressed_bytes\x18\r \x01(\x03R\x11uncompressedBytes\x12\x18\n" +
	"\amessage\x18\x14 \x01(\tR\amessage\x12\x1f\n" +
	"\vfields_json\x18\x15 \x01(\tR\n" +
	"fieldsJson\"\x1c\n" +
	"\x1aReportTaskProgressResponse\"\xa1\x04\n" +
	"\x17ReportTaskResultRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\tR\x06taskId\x12\x15\n" +
	"\x06run_id\x18\x03 \x01(\tR\x05runId\x12\x1d\n" +
	"\n" +
	"attempt_id\x18\x04 \x01(\tR\tattemptId\x12#\n" +
	"\rfencing_token\x18\x05 \x01(\tR\ffencingToken\x12\x17\n" +
	"\aboot_id\x18\x06 \x01(\tR\x06bootId\x12\x16\n" +
	"\x06status\x18\n" +
	" \x01(\tR\x06status\x12#\n" +
	"\rerror_message\x18\v \x01(\tR\ferrorMessage\x12\x1b\n" +
	"\trows_read\x18\x14 \x01(\x03R\browsRead\x12\x1d\n" +
	"\n" +
	"bytes_read\x18\x15 \x01(\x03R\tbytesRead\x12#\n" +
	"\rbytes_written\x18\x16 \x01(\x03R\fbytesWritten\x12-\n" +
	"\x12uncompressed_bytes\x18\x17 \x01(\x03R\x11uncompressedBytes\x12.\n" +
	"\x13parquet_object_keys\x18\x1e \x03(\tR\x11parquetObjectKeys\x12\"\n" +
	"\rmax_hwm_value\x18\x1f \x01(\tR\vmaxHwmValue\x12;\n" +
	"\tartifacts\x18  \x03(\v2\x1d.orabbit.v1.ArtifactIntegrityR\tartifacts\"\x8b\x04\n" +
	"\x11ArtifactIntegrity\x12\x1d\n" +
	"\n" +
	"object_key\x18\x01 \x01(\tR\tobjectKey\x12\x1b\n" +
	"\tbyte_size\x18\x02 \x01(\x03R\bbyteSize\x12\x16\n" +
	"\x06sha256\x18\x03 \x01(\tR\x06sha256\x12\x1b\n" +
	"\trow_count\x18\x04 \x01(\x03R\browCount\x12-\n" +
	"\x12schema_fingerprint\x18\x05 \x01(\tR\x11schemaFingerprint\x12\x15\n" +
	"\x06run_id\x18\x06 \x01(\tR\x05runId\x12\x17\n" +
	"\atask_id\x18\a \x01(\tR\x06taskId\x12\x1d\n" +
	"\n" +
	"attempt_id\x18\b \x01(\tR\tattemptId\x12%\n" +
	"\x0eattempt_number\x18\t \x01(\x05R\rattemptNumber\x12\x1d\n" +
	"\n" +
	"file_index\x18\n" +
	" \x01(\x05R\tfileIndex\x12%\n" +
	"\x0eformat_version\x18\v \x01(\x05R\rformatVersion\x12/\n" +
	"\x13verification_method\x18\f \x01(\tR\x12verificationMethod\x12/\n" +
	"\x13verification_status\x18\r \x01(\tR\x12verificationStatus\x12\x1f\n" +
	"\vverified_at\x18\x0e \x01(\tR\n" +
	"verifiedAt\x12\x17\n" +
	"\amax_hwm\x18\x0f \x01(\tR\x06maxHwm\"\xaa\x01\n" +
	"\x15RenewTaskLeaseRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\tR\x06taskId\x12\x1d\n" +
	"\n" +
	"attempt_id\x18\x03 \x01(\tR\tattemptId\x12#\n" +
	"\rfencing_token\x18\x04 \x01(\tR\ffencingToken\x12\x17\n" +
	"\aboot_id\x18\x05 \x01(\tR\x06bootId\"M\n" +
	"\x16RenewTaskLeaseResponse\x123\n" +
	"\x16lease_deadline_unix_ms\x18\x01 \x01(\x03R\x13leaseDeadlineUnixMs\"\xb1\x01\n" +
	"\x1cAcquireUploadCapacityRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\tR\x06taskId\x12\x1d\n" +
	"\n" +
	"attempt_id\x18\x03 \x01(\tR\tattemptId\x12#\n" +
	"\rfencing_token\x18\x04 \x01(\tR\ffencingToken\x12\x17\n" +
	"\aboot_id\x18\x05 \x01(\tR\x06bootId\"\xd2\x01\n" +
	"\x1dAcquireUploadCapacityResponse\x12\x1a\n" +
	"\bacquired\x18\x01 \x01(\bR\bacquired\x12\x19\n" +
	"\blease_id\x18\x02 \x01(\tR\aleaseId\x12\x1f\n" +
	"\vlease_token\x18\x03 \x01(\tR\n" +
	"leaseToken\x123\n" +
	"\x16lease_deadline_unix_ms\x18\x04 \x01(\x03R\x13leaseDeadlineUnixMs\x12$\n" +
	"\x0eretry_after_ms\x18\x05 \x01(\x03R\fretryAfterMs\"\xc8\x01\n" +
	"\x1cReleaseUploadCapacityRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\tR\x06taskId\x12\x1d\n" +
	"\n" +
	"attempt_id\x18\x03 \x01(\tR\tattemptId\x12\x19\n" +
	"\blease_id\x18\x04 \x01(\tR\aleaseId\x12\x1f\n" +
	"\vlease_token\x18\x05 \x01(\tR\n" +
	"leaseToken\x12\x17\n" +
	"\aboot_id\x18\x06 \x01(\tR\x06bootId\"\x1f\n" +
	"\x1dReleaseUploadCapacityResponse\"P\n" +
	"\x18ReportTaskResultResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xfa\x05\n" +
	"\fControlPlane\x12W\n" +
	"\x0eRegisterWorker\x12!.orabbit.v1.RegisterWorkerRequest\x1a\".orabbit.v1.RegisterWorkerResponse\x12H\n" +
	"\tHeartbeat\x12\x1c.orabbit.v1.HeartbeatRequest\x1a\x1d.orabbit.v1.HeartbeatResponse\x12N\n" +
	"\vRequestTask\x12\x1e.orabbit.v1.RequestTaskRequest\x1a\x1f.orabbit.v1.RequestTaskResponse\x12W\n" +
	"\x0eRenewTaskLease\x12!.orabbit.v1.RenewTaskLeaseRequest\x1a\".orabbit.v1.RenewTaskLeaseResponse\x12l\n" +
	"\x15AcquireUploadCapacity\x12(.orabbit.v1.AcquireUploadCapacityRequest\x1a).orabbit.v1.AcquireUploadCapacityResponse\x12l\n" +
	"\x15ReleaseUploadCapacity\x12(.orabbit.v1.ReleaseUploadCapacityRequest\x1a).orabbit.v1.ReleaseUploadCapacityResponse\x12c\n" +
	"\x12ReportTaskProgress\x12%.orabbit.v1.ReportTaskProgressRequest\x1a&.orabbit.v1.ReportTaskProgressResponse\x12]\n" +
	"\x10ReportTaskResult\x12#.orabbit.v1.ReportTaskResultRequest\x1a$.orabbit.v1.ReportTaskResultResponseB8Z6github.com/LevonGhukas/O_Rabbit/internal/grpcpb;grpcpbb\x06proto3"

var (
	file_proto_controlplane_proto_rawDescOnce sync.Once
	file_proto_controlplane_proto_rawDescData []byte
)

func file_proto_controlplane_proto_rawDescGZIP() []byte {
	file_proto_controlplane_proto_rawDescOnce.Do(func() {
		file_proto_controlplane_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_controlplane_proto_rawDesc), len(file_proto_controlplane_proto_rawDesc)))
	})
	return file_proto_controlplane_proto_rawDescData
}

var file_proto_controlplane_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_proto_controlplane_proto_goTypes = []any{
	(*RegisterWorkerRequest)(nil),         // 0: orabbit.v1.RegisterWorkerRequest
	(*RegisterWorkerResponse)(nil),        // 1: orabbit.v1.RegisterWorkerResponse
	(*HeartbeatRequest)(nil),              // 2: orabbit.v1.HeartbeatRequest
	(*HeartbeatResponse)(nil),             // 3: orabbit.v1.HeartbeatResponse
	(*RequestTaskRequest)(nil),            // 4: orabbit.v1.RequestTaskRequest
	(*RequestTaskResponse)(nil),           // 5: orabbit.v1.RequestTaskResponse
	(*TaskAssignment)(nil),                // 6: orabbit.v1.TaskAssignment
	(*ReportTaskProgressRequest)(nil),     // 7: orabbit.v1.ReportTaskProgressRequest
	(*ReportTaskProgressResponse)(nil),    // 8: orabbit.v1.ReportTaskProgressResponse
	(*ReportTaskResultRequest)(nil),       // 9: orabbit.v1.ReportTaskResultRequest
	(*ArtifactIntegrity)(nil),             // 10: orabbit.v1.ArtifactIntegrity
	(*RenewTaskLeaseRequest)(nil),         // 11: orabbit.v1.RenewTaskLeaseRequest
	(*RenewTaskLeaseResponse)(nil),        // 12: orabbit.v1.RenewTaskLeaseResponse
	(*AcquireUploadCapacityRequest)(nil),  // 13: orabbit.v1.AcquireUploadCapacityRequest
	(*AcquireUploadCapacityResponse)(nil), // 14: orabbit.v1.AcquireUploadCapacityResponse
	(*ReleaseUploadCapacityRequest)(nil),  // 15: orabbit.v1.ReleaseUploadCapacityRequest
	(*ReleaseUploadCapacityResponse)(nil), // 16: orabbit.v1.ReleaseUploadCapacityResponse
	(*ReportTaskResultResponse)(nil),      // 17: orabbit.v1.ReportTaskResultResponse
}
var file_proto_controlplane_proto_depIdxs = []int32{
	6,  // 0: orabbit.v1.RequestTaskResponse.task:type_name -> orabbit.v1.TaskAssignment
	10, // 1: orabbit.v1.ReportTaskResultRequest.artifacts:type_name -> orabbit.v1.ArtifactIntegrity
	0,  // 2: orabbit.v1.ControlPlane.RegisterWorker:input_type -> orabbit.v1.RegisterWorkerRequest
	2,  // 3: orabbit.v1.ControlPlane.Heartbeat:input_type -> orabbit.v1.HeartbeatRequest
	4,  // 4: orabbit.v1.ControlPlane.RequestTask:input_type -> orabbit.v1.RequestTaskRequest
	11, // 5: orabbit.v1.ControlPlane.RenewTaskLease:input_type -> orabbit.v1.RenewTaskLeaseRequest
	13, // 6: orabbit.v1.ControlPlane.AcquireUploadCapacity:input_type -> orabbit.v1.AcquireUploadCapacityRequest
	15, // 7: orabbit.v1.ControlPlane.ReleaseUploadCapacity:input_type -> orabbit.v1.ReleaseUploadCapacityRequest
	7,  // 8: orabbit.v1.ControlPlane.ReportTaskProgress:input_type -> orabbit.v1.ReportTaskProgressRequest
	9,  // 9: orabbit.v1.ControlPlane.ReportTaskResult:input_type -> orabbit.v1.ReportTaskResultRequest
	1,  // 10: orabbit.v1.ControlPlane.RegisterWorker:output_type -> orabbit.v1.RegisterWorkerResponse
	3,  // 11: orabbit.v1.ControlPlane.Heartbeat:output_type -> orabbit.v1.HeartbeatResponse
	5,  // 12: orabbit.v1.ControlPlane.RequestTask:output_type -> orabbit.v1.RequestTaskResponse
	12, // 13: orabbit.v1.ControlPlane.RenewTaskLease:output_type -> orabbit.v1.RenewTaskLeaseResponse
	14, // 14: orabbit.v1.ControlPlane.AcquireUploadCapacity:output_type -> orabbit.v1.AcquireUploadCapacityResponse
	16, // 15: orabbit.v1.ControlPlane.ReleaseUploadCapacity:output_type -> orabbit.v1.ReleaseUploadCapacityResponse
	8,  // 16: orabbit.v1.ControlPlane.ReportTaskProgress:output_type -> orabbit.v1.ReportTaskProgressResponse
	17, // 17: orabbit.v1.ControlPlane.ReportTaskResult:output_type -> orabbit.v1.ReportTaskResultResponse
	10, // [10:18] is the sub-list for method output_type
	2,  // [2:10] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_proto_controlplane_proto_init() }
func file_proto_controlplane_proto_init() {
	if File_proto_controlplane_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_controlplane_proto_rawDesc), len(file_proto_controlplane_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_controlplane_proto_goTypes,
		DependencyIndexes: file_proto_controlplane_proto_depIdxs,
		MessageInfos:      file_proto_controlplane_proto_msgTypes,
	}.Build()
	File_proto_controlplane_proto = out.File
	file_proto_controlplane_proto_goTypes = nil
	file_proto_controlplane_proto_depIdxs = nil
}
