// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: proto/controlplane.proto

package grpcpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ControlPlane_RegisterWorker_FullMethodName           = "/orabbit.v1.ControlPlane/RegisterWorker"
	ControlPlane_Heartbeat_FullMethodName                = "/orabbit.v1.ControlPlane/Heartbeat"
	ControlPlane_RequestTask_FullMethodName              = "/orabbit.v1.ControlPlane/RequestTask"
	ControlPlane_RenewTaskLease_FullMethodName           = "/orabbit.v1.ControlPlane/RenewTaskLease"
	ControlPlane_AcquireUploadCapacity_FullMethodName    = "/orabbit.v1.ControlPlane/AcquireUploadCapacity"
	ControlPlane_ReleaseUploadCapacity_FullMethodName    = "/orabbit.v1.ControlPlane/ReleaseUploadCapacity"
	ControlPlane_ReportTaskProgress_FullMethodName       = "/orabbit.v1.ControlPlane/ReportTaskProgress"
	ControlPlane_ReportTaskResult_FullMethodName         = "/orabbit.v1.ControlPlane/ReportTaskResult"
	ControlPlane_EnrollWorker_FullMethodName             = "/orabbit.v1.ControlPlane/EnrollWorker"
	ControlPlane_RenewWorkerCertificate_FullMethodName   = "/orabbit.v1.ControlPlane/RenewWorkerCertificate"
	ControlPlane_GetTaskCredentials_FullMethodName       = "/orabbit.v1.ControlPlane/GetTaskCredentials"
	ControlPlane_ReportMultipartLifecycle_FullMethodName = "/orabbit.v1.ControlPlane/ReportMultipartLifecycle"
)

// ControlPlaneClient is the client API for ControlPlane service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ControlPlaneClient interface {
	RegisterWorker(ctx context.Context, in *RegisterWorkerRequest, opts ...grpc.CallOption) (*RegisterWorkerResponse, error)
	Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
	// Pull model: worker asks for work.
	RequestTask(ctx context.Context, in *RequestTaskRequest, opts ...grpc.CallOption) (*RequestTaskResponse, error)
	RenewTaskLease(ctx context.Context, in *RenewTaskLeaseRequest, opts ...grpc.CallOption) (*RenewTaskLeaseResponse, error)
	AcquireUploadCapacity(ctx context.Context, in *AcquireUploadCapacityRequest, opts ...grpc.CallOption) (*AcquireUploadCapacityResponse, error)
	ReleaseUploadCapacity(ctx context.Context, in *ReleaseUploadCapacityRequest, opts ...grpc.CallOption) (*ReleaseUploadCapacityResponse, error)
	ReportTaskProgress(ctx context.Context, in *ReportTaskProgressRequest, opts ...grpc.CallOption) (*ReportTaskProgressResponse, error)
	ReportTaskResult(ctx context.Context, in *ReportTaskResultRequest, opts ...grpc.CallOption) (*ReportTaskResultResponse, error)
	// Worker identity. EnrollWorker is the only RPC accepted without a client
	// certificate; it exchanges a single-purpose enrollment token and a CSR for
	// a master-issued identity certificate. RenewWorkerCertificate requires the
	// current identity certificate.
	EnrollWorker(ctx context.Context, in *EnrollWorkerRequest, opts ...grpc.CallOption) (*EnrollWorkerResponse, error)
	RenewWorkerCertificate(ctx context.Context, in *RenewWorkerCertificateRequest, opts ...grpc.CallOption) (*RenewWorkerCertificateResponse, error)
	// Returns the source and target credentials for one task attempt, only to
	// the authenticated worker that currently holds that attempt's lease.
	GetTaskCredentials(ctx context.Context, in *GetTaskCredentialsRequest, opts ...grpc.CallOption) (*GetTaskCredentialsResponse, error)
	ReportMultipartLifecycle(ctx context.Context, in *ReportMultipartLifecycleRequest, opts ...grpc.CallOption) (*ReportMultipartLifecycleResponse, error)
}

type controlPlaneClient struct {
	cc grpc.ClientConnInterface
}

func NewControlPlaneClient(cc grpc.ClientConnInterface) ControlPlaneClient {
	return &controlPlaneClient{cc}
}

func (c *controlPlaneClient) RegisterWorker(ctx context.Context, in *RegisterWorkerRequest, opts ...grpc.CallOption) (*RegisterWorkerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterWorkerResponse)
	err := c.cc.Invoke(ctx, ControlPlane_RegisterWorker_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneClient) Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, ControlPlane_Heartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneClient) RequestTask(ctx context.Context, in *RequestTaskRequest, opts ...grpc.CallOption) (*RequestTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RequestTaskResponse)
	err := c.cc.Invoke(ctx, ControlPlane_RequestTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneClient) RenewTaskLease(ctx context.Context, in *RenewTaskLeaseRequest, opts ...grpc.CallOption) (*RenewTaskLeaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RenewTaskLeaseResponse)
	err := c.cc.Invoke(ctx, ControlPlane_RenewTaskLease_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneClient) AcquireUploadCapacity(ctx context.Context, in *AcquireUploadCapacityRequest, opts ...grpc.CallOption) (*AcquireUploadCapacityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AcquireUploadCapacityResponse)
	err := c.cc.Invoke(ctx, ControlPlane_AcquireUploadCapacity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneClient) ReleaseUploadCapacity(ctx context.Context, in *ReleaseUploadCapacityRequest, opts ...grpc.CallOption) (*ReleaseUploadCapacityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReleaseUploadCapacityResponse)
	err := c.cc.Invoke(ctx, ControlPlane_ReleaseUploadCapacity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneClient) ReportTaskProgress(ctx context.Context, in *ReportTaskProgressRequest, opts ...grpc.CallOption) (*ReportTaskProgressResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportTaskProgressResponse)
	err := c.cc.Invoke(ctx, ControlPlane_ReportTaskProgress_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneClient) ReportTaskResult(ctx context.Context, in *ReportTaskResultRequest, opts ...grpc.CallOption) (*ReportTaskResultResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportTaskResultResponse)
	err := c.cc.Invoke(ctx, ControlPlane_ReportTaskResult_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneClient) EnrollWorker(ctx context.Context, in *EnrollWorkerRequest, opts ...grpc.CallOption) (*EnrollWorkerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnrollWorkerResponse)
	err := c.cc.Invoke(ctx, ControlPlane_EnrollWorker_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneClient) RenewWorkerCertificate(ctx context.Context, in *RenewWorkerCertificateRequest, opts ...grpc.CallOption) (*RenewWorkerCertificateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RenewWorkerCertificateResponse)
	err := c.cc.Invoke(ctx, ControlPlane_RenewWorkerCertificate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneClient) GetTaskCredentials(ctx context.Context, in *GetTaskCredentialsRequest, opts ...grpc.CallOption) (*GetTaskCredentialsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTaskCredentialsResponse)
	err := c.cc.Invoke(ctx, ControlPlane_GetTaskCredentials_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneClient) ReportMultipartLifecycle(ctx context.Context, in *ReportMultipartLifecycleRequest, opts ...grpc.CallOption) (*ReportMultipartLifecycleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportMultipartLifecycleResponse)
	err := c.cc.Invoke(ctx, ControlPlane_ReportMultipartLifecycle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ControlPlaneServer is the server API for ControlPlane service.
// All implementations must embed UnimplementedControlPlaneServer
// for forward compatibility.
type ControlPlaneServer interface {
	RegisterWorker(context.Context, *RegisterWorkerRequest) (*RegisterWorkerResponse, error)
	Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
	// Pull model: worker asks for work.
	RequestTask(context.Context, *RequestTaskRequest) (*RequestTaskResponse, error)
	RenewTaskLease(context.Context, *RenewTaskLeaseRequest) (*RenewTaskLeaseResponse, error)
	AcquireUploadCapacity(context.Context, *AcquireUploadCapacityRequest) (*AcquireUploadCapacityResponse, error)
	ReleaseUploadCapacity(context.Context, *ReleaseUploadCapacityRequest) (*ReleaseUploadCapacityResponse, error)
	ReportTaskProgress(context.Context, *ReportTaskProgressRequest) (*ReportTaskProgressResponse, error)
	ReportTaskResult(context.Context, *ReportTaskResultRequest) (*ReportTaskResultResponse, error)
	// Worker identity. EnrollWorker is the only RPC accepted without a client
	// certificate; it exchanges a single-purpose enrollment token and a CSR for
	// a master-issued identity certificate. RenewWorkerCertificate requires the
	// current identity certificate.
	EnrollWorker(context.Context, *EnrollWorkerRequest) (*EnrollWorkerResponse, error)
	RenewWorkerCertificate(context.Context, *RenewWorkerCertificateRequest) (*RenewWorkerCertificateResponse, error)
	// Returns the source and target credentials for one task attempt, only to
	// the authenticated worker that currently holds that attempt's lease.
	GetTaskCredentials(context.Context, *GetTaskCredentialsRequest) (*GetTaskCredentialsResponse, error)
	ReportMultipartLifecycle(context.Context, *ReportMultipartLifecycleRequest) (*ReportMultipartLifecycleResponse, error)
	mustEmbedUnimplementedControlPlaneServer()
}

// UnimplementedControlPlaneServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedControlPlaneServer struct{}

func (UnimplementedControlPlaneServer) RegisterWorker(context.Context, *RegisterWorkerRequest) (*RegisterWorkerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterWorker not implemented")
}
func (UnimplementedControlPlaneServer) Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedControlPlaneServer) RequestTask(context.Context, *RequestTaskRequest) (*RequestTaskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RequestTask not implemented")
}
func (UnimplementedControlPlaneServer) RenewTaskLease(context.Context, *RenewTaskLeaseRequest) (*RenewTaskLeaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RenewTaskLease not implemented")
}
func (UnimplementedControlPlaneServer) AcquireUploadCapacity(context.Context, *AcquireUploadCapacityRequest) (*AcquireUploadCapacityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AcquireUploadCapacity not implemented")
}
func (UnimplementedControlPlaneServer) ReleaseUploadCapacity(context.Context, *ReleaseUploadCapacityRequest) (*ReleaseUploadCapacityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReleaseUploadCapacity not implemented")
}
func (UnimplementedControlPlaneServer) ReportTaskProgress(context.Context, *ReportTaskProgressRequest) (*ReportTaskProgressResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportTaskProgress not implemented")
}
func (UnimplementedControlPlaneServer) ReportTaskResult(context.Context, *ReportTaskResultRequest) (*ReportTaskResultResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportTaskResult not implemented")
}
func (UnimplementedControlPlaneServer) EnrollWorker(context.Context, *EnrollWorkerRequest) (*EnrollWorkerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EnrollWorker not implemented")
}
func (UnimplementedControlPlaneServer) RenewWorkerCertificate(context.Context, *RenewWorkerCertificateRequest) (*RenewWorkerCertificateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RenewWorkerCertificate not implemented")
}
func (UnimplementedControlPlaneServer) GetTaskCredentials(context.Context, *GetTaskCredentialsRequest) (*GetTaskCredentialsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTaskCredentials not implemented")
}
func (UnimplementedControlPlaneServer) ReportMultipartLifecycle(context.Context, *ReportMultipartLifecycleRequest) (*ReportMultipartLifecycleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportMultipartLifecycle not implemented")
}
func (UnimplementedControlPlaneServer) mustEmbedUnimplementedControlPlaneServer() {}
func (UnimplementedControlPlaneServer) testEmbeddedByValue()                      {}

// UnsafeControlPlaneServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ControlPlaneServer will
// result in compilation errors.
type UnsafeControlPlaneServer interface {
	mustEmbedUnimplementedControlPlaneServer()
}

func RegisterControlPlaneServer(s grpc.ServiceRegistrar, srv ControlPlaneServer) {
	// If the following call panics, it indicates UnimplementedControlPlaneServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ControlPlane_ServiceDesc, srv)
}

func _ControlPlane_RegisterWorker_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterWorkerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServer).RegisterWorker(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlane_RegisterWorker_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServer).RegisterWorker(ctx, req.(*RegisterWorkerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlane_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlane_Heartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServer).Heartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlane_RequestTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServer).RequestTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlane_RequestTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServer).RequestTask(ctx, req.(*RequestTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlane_RenewTaskLease_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenewTaskLeaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServer).RenewTaskLease(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlane_RenewTaskLease_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServer).RenewTaskLease(ctx, req.(*RenewTaskLeaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlane_AcquireUploadCapacity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcquireUploadCapacityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServer).AcquireUploadCapacity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlane_AcquireUploadCapacity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServer).AcquireUploadCapacity(ctx, req.(*AcquireUploadCapacityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlane_ReleaseUploadCapacity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReleaseUploadCapacityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServer).ReleaseUploadCapacity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlane_ReleaseUploadCapacity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServer).ReleaseUploadCapacity(ctx, req.(*ReleaseUploadCapacityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlane_ReportTaskProgress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportTaskProgressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServer).ReportTaskProgress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlane_ReportTaskProgress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServer).ReportTaskProgress(ctx, req.(*ReportTaskProgressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlane_ReportTaskResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportTaskResultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServer).ReportTaskResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlane_ReportTaskResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServer).ReportTaskResult(ctx, req.(*ReportTaskResultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlane_EnrollWorker_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnrollWorkerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServer).EnrollWorker(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlane_EnrollWorker_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServer).EnrollWorker(ctx, req.(*EnrollWorkerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlane_RenewWorkerCertificate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenewWorkerCertificateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServer).RenewWorkerCertificate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlane_RenewWorkerCertificate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServer).RenewWorkerCertificate(ctx, req.(*RenewWorkerCertificateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlane_GetTaskCredentials_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTaskCredentialsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServer).GetTaskCredentials(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlane_GetTaskCredentials_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServer).GetTaskCredentials(ctx, req.(*GetTaskCredentialsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlane_ReportMultipartLifecycle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportMultipartLifecycleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServer).ReportMultipartLifecycle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlane_ReportMultipartLifecycle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServer).ReportMultipartLifecycle(ctx, req.(*ReportMultipartLifecycleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ControlPlane_ServiceDesc is the grpc.ServiceDesc for ControlPlane service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ControlPlane_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "orabbit.v1.ControlPlane",
	HandlerType: (*ControlPlaneServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterWorker",
			Handler:    _ControlPlane_RegisterWorker_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _ControlPlane_Heartbeat_Handler,
		},
		{
			MethodName: "RequestTask",
			Handler:    _ControlPlane_RequestTask_Handler,
		},
		{
			MethodName: "RenewTaskLease",
			Handler:    _ControlPlane_RenewTaskLease_Handler,
		},
		{
			MethodName: "AcquireUploadCapacity",
			Handler:    _ControlPlane_AcquireUploadCapacity_Handler,
		},
		{
			MethodName: "ReleaseUploadCapacity",
			Handler:    _ControlPlane_ReleaseUploadCapacity_Handler,
		},
		{
			MethodName: "ReportTaskProgress",
			Handler:    _ControlPlane_ReportTaskProgress_Handler,
		},
		{
			MethodName: "ReportTaskResult",
			Handler:    _ControlPlane_ReportTaskResult_Handler,
		},
		{
			MethodName: "EnrollWorker",
			Handler:    _ControlPlane_EnrollWorker_Handler,
		},
		{
			MethodName: "RenewWorkerCertificate",
			Handler:    _ControlPlane_RenewWorkerCertificate_Handler,
		},
		{
			MethodName: "GetTaskCredentials",
			Handler:    _ControlPlane_GetTaskCredentials_Handler,
		},
		{
			MethodName: "ReportMultipartLifecycle",
			Handler:    _ControlPlane_ReportMultipartLifecycle_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/controlplane.proto",
}
