package orabbitcli

import (
	"context"
	"errors"
	"flag"
	"fmt"
	"io"
	"os"
)

func usage(w io.Writer) {
	tw := newTextBlockWriter(w)
	tw.title(fmt.Sprintf("%s - Orabbit client CLI", CLIName))
	tw.blank()
	tw.section("Usage")
	tw.command(fmt.Sprintf("%s <command> [options]", CLIName))
	tw.command(fmt.Sprintf("%s help [command] [subcommand]", CLIName))
	tw.blank()
	tw.section("Commands")
	tw.item("stack", "Manage local master/worker processes")
	tw.item("run", "Interactive and non-interactive run operations")
	tw.item("help", "Show help for commands and subcommands")
	tw.blank()
	tw.section("Examples")
	tw.command(fmt.Sprintf("%s stack start master worker --count 4", CLIName))
	tw.command(fmt.Sprintf("%s stack start worker --master-addr master.example.internal:9102 --count 4", CLIName))
	tw.command(fmt.Sprintf("%s run interactive", CLIName))
	tw.command(fmt.Sprintf("%s run submit --file ./run.yaml", CLIName))
	tw.command(fmt.Sprintf("%s run watch <run-id>", CLIName))
	tw.command(fmt.Sprintf("%s run cancel <run-id>", CLIName))
	tw.command(fmt.Sprintf("%s run diagnose <run-id>", CLIName))
	tw.command(fmt.Sprintf("%s run recover <run-id> --action reconcile_commit --reason \"stale commit\"", CLIName))
	tw.command(fmt.Sprintf("%s stack status --json", CLIName))
	tw.command(fmt.Sprintf("%s stack stop --force", CLIName))
	tw.blank()
	tw.section("Notes")
	tw.bullet("`stack` manages local daemons; `run interactive` is the guided path and `run submit` is the non-interactive path.")
	tw.blank()
	tw.section("Install")
	tw.command("go install ./cmd/orabbit-client")
	tw.blank()
	tw.section("Local stack")
	tw.bullet("Build or install orabbit-master and orabbit-worker next to orabbit-client, or pass --master-bin/--worker-bin.")
}

func cmdHelp(ctx context.Context, args []string) int {
	return cliRootCommand().helpTopic(ctx, args)
}

func parseCommandFlags(fs *flag.FlagSet, args []string, renderHelp func(io.Writer, *flag.FlagSet)) (handled bool, exit int) {
	fs.SetOutput(io.Discard)
	if err := fs.Parse(args); err != nil {
		if errors.Is(err, flag.ErrHelp) {
			renderHelp(os.Stdout, fs)
			return true, exitSuccess
		}
		fmt.Fprintln(os.Stderr, err)
		renderHelp(os.Stderr, fs)
		return true, exitUsage
	}
	return false, exitSuccess
}

func renderStackHelp(w io.Writer) {
	tw := newTextBlockWriter(w)
	tw.title(fmt.Sprintf("%s stack - manage local master/worker processes", CLIName))
	tw.blank()
	tw.section("Usage")
	tw.command(fmt.Sprintf("%s stack <command> [options]", CLIName))
	tw.command(fmt.Sprintf("%s stack start ...", CLIName))
	tw.command(fmt.Sprintf("%s stack stop ...", CLIName))
	tw.command(fmt.Sprintf("%s stack status ...", CLIName))
	tw.blank()
	tw.section("Commands")
	tw.item("start", "Start local master and/or worker helper processes")
	tw.item("stop", "Stop local master/worker helper processes")
	tw.item("status", "List local/remote master and worker status")
	tw.blank()
	tw.section("Notes")
	tw.bullet("`stack status` prefers managed local state for the default local runtime, then falls back to master APIs and process inspection.")
}

func renderStackStartHelp(w io.Writer, fs *flag.FlagSet) {
	fs.SetOutput(w)
	tw := newTextBlockWriter(w)
	tw.title(fmt.Sprintf("%s stack start - start local master and/or worker helper processes in the foreground", CLIName))
	tw.blank()
	tw.section("Usage")
	tw.command(fmt.Sprintf("%s stack start master", CLIName))
	tw.command(fmt.Sprintf("%s stack start worker --master-addr 127.0.0.1:9102 --count 4", CLIName))
	tw.command(fmt.Sprintf("%s stack start master worker --count 4", CLIName))
	tw.blank()
	tw.section("Components")
	tw.item("master", "Start the master process.")
	tw.item("worker", "Start one or more worker processes.")
	tw.bullet("In the current CLI, components are positional and must appear before flags.")
	tw.blank()
	tw.section("Behavior")
	tw.bullet("Runs helper processes in the foreground and re-emits helper logs with [master] / [worker:...] prefixes.")
	tw.bullet("Reuses an already-healthy local master instead of starting a duplicate.")
	tw.bullet("Workers connect either to the started master or to --master-addr.")
	tw.bullet("Local daemons are resolved next to orabbit-client by default; use --master-bin/--worker-bin to override.")
	tw.bullet("--worker-log-level and --worker-log-format are passed through to local worker processes when workers are started.")
	tw.blank()
	tw.section("Output")
	tw.bullet("--quiet suppresses non-essential client progress and helper daemon log forwarding.")
	tw.bullet("--verbose shows additional client progress details.")
	tw.blank()
	tw.section("Flags")
	tw.flags(fs)
}

func renderRunGroupHelp(w io.Writer) {
	tw := newTextBlockWriter(w)
	tw.title(fmt.Sprintf("%s run - interactive and non-interactive run operations", CLIName))
	tw.blank()
	tw.section("Usage")
	tw.command(fmt.Sprintf("%s run <command> [options]", CLIName))
	tw.command(fmt.Sprintf("%s run interactive", CLIName))
	tw.command(fmt.Sprintf("%s run submit --file ./run.yaml", CLIName))
	tw.command(fmt.Sprintf("%s run watch <run-id>", CLIName))
	tw.command(fmt.Sprintf("%s run cancel <run-id>", CLIName))
	tw.blank()
	tw.section("Commands")
	tw.item("interactive", "Interactive guided run flow")
	tw.item("submit", "Submit a run from a YAML/JSON spec file")
	tw.item("watch", "Stream events for an existing run")
	tw.item("cancel", "Cancel an existing run")
	tw.item("diagnose", "Print a redacted lifecycle diagnosis for a run")
	tw.item("recover", "Request a narrow, audited lifecycle recovery action")
	tw.blank()
	tw.section("Notes")
	tw.bullet("`run interactive` is the primary guided workflow.")
	tw.bullet("`run submit` is the non-interactive, file-based path.")
}

func renderRunInteractiveHelp(w io.Writer, fs *flag.FlagSet) {
	fs.SetOutput(w)
	tw := newTextBlockWriter(w)
	tw.title(fmt.Sprintf("%s run interactive - interactive launcher plus local-stack orchestration", CLIName))
	tw.blank()
	tw.section("Usage")
	tw.command(fmt.Sprintf("%s run interactive", CLIName))
	tw.command(fmt.Sprintf("%s run interactive \\", CLIName))
	tw.command("    --master-http http://master.example.internal:9100 \\")
	tw.command("    --master-grpc master.example.internal:9102 \\")
	tw.command("    --local-workers=false")
	tw.blank()
	tw.section("Behavior")
	tw.bullet("Normal mode prompts for the essential source, target, Iceberg, and review fields only.")
	tw.bullet("Use --advanced to expose low-level storage, worker, and tuning prompts.")
	tw.bullet("Can start a local master if one is not already running.")
	tw.bullet("Can start local workers on this machine unless --local-workers=false.")
	tw.bullet("Automatic performance tuning is enabled by default in normal mode.")
	tw.bullet("Starts a run, streams events, and can register Parquet parts into Iceberg after success.")
	tw.blank()
	tw.section("Notes")
	tw.bullet("`run interactive` requires a TTY on stdin.")
	tw.bullet("--master-http targets an existing master; --master-grpc is used for local workers against that master.")
	tw.bullet("Local daemons are resolved next to orabbit-client by default; use --master-bin/--worker-bin to override.")
	tw.bullet("--worker-log-level and --worker-log-format are passed through to local worker processes when --local-workers=true.")
	tw.bullet("Secret prompts such as the S3 secret access key use hidden input.")
	tw.bullet("Local daemon logs are re-emitted with [master] / [worker:...] prefixes while the client is running.")
	tw.bullet("--quiet suppresses daemon log forwarding, streamed run chatter, and non-essential client progress.")
	tw.bullet("--verbose shows additional client progress details.")
	tw.blank()
	tw.section("Flags")
	tw.flags(fs)
}

func renderRunWatchHelp(w io.Writer, fs *flag.FlagSet) {
	fs.SetOutput(w)
	tw := newTextBlockWriter(w)
	tw.title(fmt.Sprintf("%s run watch - stream events for an existing run", CLIName))
	tw.blank()
	tw.section("Usage")
	tw.command(fmt.Sprintf("%s run watch <run-id>", CLIName))
	tw.command(fmt.Sprintf("%s run watch <run-id> --master-http http://master.example.internal:9100", CLIName))
	tw.blank()
	tw.section("Behavior")
	tw.bullet("Verifies that the run exists, then follows its SSE event stream.")
	tw.bullet("If the run is already terminal, prints the terminal status and exits without canceling anything.")
	tw.bullet("Ctrl+C stops watching and exits with code 130; it does not cancel the run.")
	tw.blank()
	tw.section("Flags")
	tw.flags(fs)
}

func renderRunSubmitHelp(w io.Writer, fs *flag.FlagSet) {
	fs.SetOutput(w)
	tw := newTextBlockWriter(w)
	tw.title(fmt.Sprintf("%s run submit - submit a run from a YAML/JSON spec file", CLIName))
	tw.blank()
	tw.section("Usage")
	tw.command(fmt.Sprintf("%s run submit --file ./run.yaml", CLIName))
	tw.command(fmt.Sprintf("%s run submit --file ./run.json --master-http http://master.example.internal:9100", CLIName))
	tw.blank()
	tw.section("Behavior")
	tw.bullet("Loads a structured run spec from YAML or JSON.")
	tw.bullet("Validates the file strictly before making API calls.")
	tw.bullet("Upserts source/target connections and the job by name, then starts a run.")
	tw.bullet("Prints the run ID and a follow-up watch command.")
	tw.blank()
	tw.section("Spec shape")
	tw.bullet("Top-level sections: master (optional), source, target, job.")
	tw.bullet("source.name, target.name, and job.name are upsert identifiers on the master.")
	tw.bullet("source.engine supports the same engines as the current interactive flow.")
	tw.bullet("master.http in the file is optional and can be overridden by --master-http.")
	tw.blank()
	tw.section("Notes")
	tw.bullet("`run submit` is the non-interactive path; it does not prompt and does not start local daemons.")
	tw.bullet("Use `run watch <run-id>` to follow the submitted run.")
	tw.blank()
	tw.section("Flags")
	tw.flags(fs)
}

func renderRunCancelHelp(w io.Writer, fs *flag.FlagSet) {
	fs.SetOutput(w)
	tw := newTextBlockWriter(w)
	tw.title(fmt.Sprintf("%s run cancel - cancel an existing run", CLIName))
	tw.blank()
	tw.section("Usage")
	tw.command(fmt.Sprintf("%s run cancel <run-id>", CLIName))
	tw.command(fmt.Sprintf("%s run cancel <run-id> --master-http http://master.example.internal:9100", CLIName))
	tw.blank()
	tw.section("Behavior")
	tw.bullet("Sends explicit cancel intent to the master for the given run.")
	tw.bullet("Marks the run CANCELED and prevents further scheduling for that run.")
	tw.bullet("Pending tasks are marked CANCELED; already-running tasks now stop cooperatively at worker checkpoints when practical.")
	tw.blank()
	tw.section("Flags")
	tw.flags(fs)
}

func renderRunDiagnoseHelp(w io.Writer, fs *flag.FlagSet) {
	fs.SetOutput(w)
	tw := newTextBlockWriter(w)
	tw.title(fmt.Sprintf("%s run diagnose - print redacted lifecycle state and the suggested next action", CLIName))
	tw.blank()
	tw.section("Usage")
	tw.command(fmt.Sprintf("%s run diagnose <run-id>", CLIName))
	tw.command(fmt.Sprintf("%s run diagnose <run-id> --master-http http://master.example.internal:9100", CLIName))
	tw.blank()
	tw.section("Behavior")
	tw.bullet("Prints JSON containing bounded task/attempt, commit, registration, and reconciliation state.")
	tw.bullet("Fencing tokens, credentials, DSNs, object keys, and host-local paths are omitted.")
	tw.blank()
	tw.section("Flags")
	tw.flags(fs)
}

func renderRunRecoverHelp(w io.Writer, fs *flag.FlagSet) {
	fs.SetOutput(w)
	tw := newTextBlockWriter(w)
	tw.title(fmt.Sprintf("%s run recover - request a narrow audited recovery action", CLIName))
	tw.blank()
	tw.section("Usage")
	tw.command(fmt.Sprintf("%s run recover <run-id> --action reconcile_commit --reason \"live scan overdue\"", CLIName))
	tw.command(fmt.Sprintf("%s run recover <run-id> --action registration_retry --reason \"catalog outage resolved\"", CLIName))
	tw.blank()
	tw.section("Safety")
	tw.bullet("The master rechecks durable state and leadership before every action.")
	tw.bullet("Catalog mutation replay is refused after a durable receipt.")
	tw.bullet("acknowledge_quarantine records operator review but does not alter terminal task state.")
	tw.blank()
	tw.section("Flags")
	tw.flags(fs)
}

func renderStackStopHelp(w io.Writer, fs *flag.FlagSet) {
	fs.SetOutput(w)
	tw := newTextBlockWriter(w)
	tw.title(fmt.Sprintf("%s stack stop - stop local master/worker helper processes", CLIName))
	tw.blank()
	tw.section("Usage")
	tw.command(fmt.Sprintf("%s stack stop", CLIName))
	tw.command(fmt.Sprintf("%s stack stop --force", CLIName))
	tw.command(fmt.Sprintf("%s stack stop --all --grpc-addr 127.0.0.1:9102 --force", CLIName))
	tw.blank()
	tw.section("Behavior")
	tw.bullet("Default mode first matches client-managed processes recorded in the managed state under --gocache.")
	tw.bullet("If no managed state matches are available, default mode falls back to legacy managed-runtime marker matching for compatibility.")
	tw.bullet("--all enables broader best-effort matching based on process inspection heuristics.")
	tw.bullet("Sends SIGTERM first, then SIGKILL if processes do not exit in time.")
	tw.blank()
	tw.section("Notes")
	tw.bullet("--all enables broader matching for master/worker processes on Unix-like systems.")
	tw.bullet("--dry-run prints the exact matched targets without signaling them.")
	tw.blank()
	tw.section("Flags")
	tw.flags(fs)
}

func renderStackStatusHelp(w io.Writer, fs *flag.FlagSet) {
	fs.SetOutput(w)
	tw := newTextBlockWriter(w)
	tw.title(fmt.Sprintf("%s stack status - list running master/worker processes", CLIName))
	tw.blank()
	tw.section("Usage")
	tw.command(fmt.Sprintf("%s stack status", CLIName))
	tw.command(fmt.Sprintf("%s stack status --json", CLIName))
	tw.command(fmt.Sprintf("%s stack status -v", CLIName))
	tw.blank()
	tw.section("Behavior")
	tw.bullet("For the default local master target, prefers managed state from --gocache for client-managed local processes.")
	tw.bullet("Otherwise prefers querying the master via /status and /workers at --http-base.")
	tw.bullet("Falls back to best-effort process inspection only when managed state and master APIs do not provide results.")
	tw.bullet("When querying a live master through the API path, also reports gRPC readiness.")
	tw.blank()
	tw.section("Notes")
	tw.bullet("`--json` emits a stable schema with schema_version/source/http_base/items.")
	tw.bullet("Backend differences are explicit in source=managed_state, source=master_api, or source=process_scan; unavailable fields are null.")
	tw.blank()
	tw.section("Flags")
	tw.flags(fs)
}
